DROP TABLE IF EXISTS F_B3;
DROP TABLE IF EXISTS COT_HISTORICA;
DROP TABLE IF EXISTS D_DATA;
DROP TABLE IF EXISTS D_BDI;
DROP TABLE IF EXISTS D_ESPECIFICACAO;
DROP TABLE IF EXISTS D_NOMEACAO;
DROP TABLE IF EXISTS D_INDOPC;
DROP TABLE IF EXISTS D_TPMERC;

CREATE TABLE COT_HISTORICA
(
    TIPREG  BIGINT,
    DATPREG DATE,
    CODBDI  VARCHAR(30),
    CODNEG  VARCHAR(30),
    TPMERC  BIGINT,
    NOMRES  VARCHAR(100),
    ESPECI  VARCHAR(30),
    PRAZOT  VARCHAR(30),
    MODREF  VARCHAR(30),
    PREABE  NUMERIC,
    PREMAX  NUMERIC,
    PREMIN  NUMERIC,
    PREMED  NUMERIC,
    PREULT  NUMERIC,
    PREOFC  NUMERIC,
    PREOFV  NUMERIC,
    TOTNEG  BIGINT,
    QUATOT  BIGINT,
    VOLTOT  NUMERIC,
    PREEXE  NUMERIC,
    INDOPC  BIGINT,
    DATVEN  DATE,
    FATCOT  BIGINT,
    PTOEXE  NUMERIC,
    CODISI  VARCHAR(30),
    DISMES  BIGINT

);

CREATE TABLE D_DATA
(
    ID                SERIAL PRIMARY KEY,
    COD_TEMPO         VARCHAR(30) NOT NULL,
    _DATA             DATE        NOT NULL UNIQUE,
    NUMERO_DIA_SEMANA INTEGER     NOT NULL,
    NUMERO_MES        INTEGER     NOT NULL,
    NUMERO_ANO        INTEGER     NOT NULL,
    NUMERO_TRIMESTRE  INTEGER     NOT NULL,
    NUMERO_SEMESTRE   INTEGER     NOT NULL,
    NOME_TRIMESTRE    VARCHAR(30) NOT NULL,
    NOME_SEMESTRE     VARCHAR(30) NOT NULL,
    NOME_MES          VARCHAR(30)
);

CREATE TABLE D_BDI
(
    ID      SERIAL PRIMARY KEY,
    COD_BDI VARCHAR(30) NOT NULL UNIQUE,
    NOME    VARCHAR(60) NOT NULL
);

CREATE TABLE D_ESPECIFICACAO
(
    ID        SERIAL PRIMARY KEY,
    FIDC      VARCHAR(30)  NOT NULL UNIQUE,
    DESCRICAO VARCHAR(100) NOT NULL
);

CREATE TABLE D_INDOPC
(
    ID         SERIAL PRIMARY KEY,
    COD_INDOPC INTEGER      NOT NULL UNIQUE,
    SIGLA      VARCHAR(30)  NOT NULL,
    NOME       VARCHAR(100) NOT NULL
);

CREATE TABLE D_TPMERC
(
    ID         SERIAL PRIMARY KEY,
    COD_TPMERC INTEGER      NOT NULL UNIQUE,
    NOME       VARCHAR(100) NOT NULL
);

CREATE TABLE D_NOMEACAO
(
    ID   SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE F_B3
(
    TIPREG           BIGINT,
    ID_DATPREG       INTEGER,
    ID_BDI           INTEGER,
    CODNEG           VARCHAR(30),
    ID_TPMERC        INTEGER,
    ID_NOMEACAO      INTEGER,
    ID_ESPECIFICACAO INTEGER,
    PRAZOT           VARCHAR(30),
    MODREF           VARCHAR(30),
    PREABE           NUMERIC,
    PREMAX           NUMERIC,
    PREMIN           NUMERIC,
    PREMED           NUMERIC,
    PREULT           NUMERIC,
    PREOFC           NUMERIC,
    PREOFV           NUMERIC,
    TOTNEG           BIGINT,
    QUATOT           BIGINT,
    VOLTOT           NUMERIC,
    PREEXE           NUMERIC,
    ID_INDOPC        INTEGER,
    DATVEN           DATE,
    FATCOT           BIGINT,
    PTOEXE           NUMERIC,
    CODISI           VARCHAR(30),
    DISMES           BIGINT,

    CONSTRAINT FK_BDI FOREIGN KEY (ID_BDI) REFERENCES D_BDI (ID),
    CONSTRAINT FK_TPMERC FOREIGN KEY (ID_TPMERC) REFERENCES D_TPMERC (ID),
    CONSTRAINT FK_NOMEACAO FOREIGN KEY (ID_NOMEACAO) REFERENCES D_NOMEACAO (ID),
    CONSTRAINT FK_ESPECIFICACAO FOREIGN KEY (ID_ESPECIFICACAO) REFERENCES D_ESPECIFICACAO (ID),
    CONSTRAINT FK_INDOPC FOREIGN KEY (ID_INDOPC) REFERENCES D_INDOPC (ID),
    CONSTRAINT FK_DATPREG FOREIGN KEY (ID_DATPREG) REFERENCES D_DATA (ID)
);

select *
from f_b3;